2022-02-10 14:29:12 CET:grace_p2p_client:INFO:loading ctx from store.json
2022-02-10 14:29:12 CET:grace_p2p_client:INFO:starting aNetworkId: 1CF094259E06664DA5504A5E1C551759 aNodeId: 1d37319760cfbc42b559833448f60ba6
2022-02-10 14:29:12 CET:grace_p2p_client:INFO:listening on 0.0.0.0:52829
2022-02-10 14:29:12 CET:grace_p2p_client:INFO:starting received thread
2022-02-10 14:29:12 CET:grace_p2p_client:INFO:NodePktHeader(bKey=0x80, bVersion=0x37, aNetworkId=1cf094259e06664da5504a5e1c551759, aNodeId=1d37319760cfbc42b559833448f60ba6, bFrameId=0x7, dwWaterMark=0xecf9, dwCrc32=0x0)
2022-02-10 14:29:12 CET:grace_p2p_client:INFO:NodePktInvitation(hdr=NodePktDataHeader(bCmdId=0x1, dwSessionId=0xecf9), aInvitationId=e1bce7bc8cd00f438889122eebc7d329, aNodeId=1d37319760cfbc42b559833448f60ba6, wNodeBindedPort=0xce5d)
2022-02-10 14:29:12 CET:grace_p2p_client:INFO:45.129.137.237:33964 | send | size 90 | 80379c7014a51e86e6cd25d0cade9cd597d99db7b117e04f3cc235d903b4c8768b2607796c8080da7ab3e3270000006c8f683581796c8080613c673c0c508fc3080992ae6b4753a99db7b117e04f3cc235d903b4c8768b26dd4e
2022-02-10 14:29:12 CET:grace_p2p_client:ERROR:fatal error
Traceback (most recent call last):
  File "../tools/grace_p2p_client.py", line 490, in <module>
    emulate()
  File "../tools/grace_p2p_client.py", line 471, in emulate
    bot.start()
  File "../tools/grace_p2p_client.py", line 197, in start
    self.send_invitation(addr)
  File "../tools/grace_p2p_client.py", line 314, in send_invitation
    self.s.sendto(data, addr)
TypeError: sendto(): AF_INET address must be tuple, not list
