2022-02-10 12:56:17 CET:grace_p2p_client:ERROR:fatal error
Traceback (most recent call last):
  File "../tools/grace_p2p_client.py", line 482, in <module>
    emulate()
  File "../tools/grace_p2p_client.py", line 461, in emulate
    bot = P2PBot()
  File "../tools/grace_p2p_client.py", line 164, in __init__
    with open(self.store_fn, "r") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'store.json'
